FROM                eb-docker:base
MAINTAINER          sang93423@gmail.com

ENV                 BUILD_MODE              local
ENV                 DJANGO_SETTINGS_MODULE config.settings.${BUILD_MODE}

COPY                .   /srv/project
