FROM                python:3.6.5-slim
MAINTAINER          sang93423@gmail.com

# pip install uwsgi
RUN                 apt -y update && apt -y dist-upgrade
RUN                 apt -y install build-essential
RUN                 apt -y install nginx supervisor

# 로컬의 requirements.txt 파일을 /srv에 복사 후 pip install실행
# (build하는 환경에 requiremets.txt가 있어야 함!)
COPY                ./requirements.txt   /srv/
RUN                 pip install -r /srv/requirements.txt